version: 2.1

executors:
  java21:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project

jobs:
  test:
    executor: java21
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ arch }}-{{ .Branch }}-{{ checksum "pom.xml" }}
            - m2-{{ arch }}-
      - run:
          name: Run unit tests
          command: mvn -q -B test
      - save_cache:
          key: m2-{{ arch }}-{{ .Branch }}-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

  build:
    executor: java21
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ arch }}-{{ .Branch }}-{{ checksum "pom.xml" }}
            - m2-{{ arch }}-
      - run:
          name: Build fat JAR
          command: mvn -q -B -DskipTests package spring-boot:repackage
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar

  docker_build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 24.0.5
      - run:
          name: Build Docker image
          command: |
            : "${DOCKER_IMAGE:=ghcr.io/<your-username>/<your-repo>:${CIRCLE_SHA1}}"
            docker build -t "$DOCKER_IMAGE" .
      # Optional push (requires registry login via project env vars)
      # - run: |
      #     echo "$CR_PAT" | docker login ghcr.io -u <your-username> --password-stdin
      #     docker push "$DOCKER_IMAGE"

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires: [test]
      - docker_build:
          requires: [build]
