apiVersion: v1
kind: Secret
metadata:
  name: txapi-secrets
  namespace: tx
type: Opaque
stringData:
  PUBLIC_PEM: |
    -----BEGIN PUBLIC KEY-----
    YOUR_PUBLIC_KEY_HERE
    -----END PUBLIC KEY-----
