spring:
  application:
    name: transactions-api
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  baseCurrency: CHF
  fxUrlTemplate: "https://api.exchangerate.host/latest?base={base}"
